runtime: python27
api_version: 1
threadsafe: yes

handlers:
  - url: /
    static_files: dist/noise-to-help-app/index.html
    upload: dist/noise-to-help-app/index.html
  - url: /
    static_dir: dist/noise-to-help-app

skip_files:
  - ^(?!dist)
