# Stage 0: compile angular frontend
FROM node:10.16.0 as build
WORKDIR /app
COPY . .
RUN npm i
RUN npm run build-production

# Stage 1: serve app with nginx server
FROM nginx:1.15
COPY --from=build /app/dist/noise-to-help-app /usr/share/nginx/app
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3202
